### ISSUE TITLE
unofficial-wineskin is not installable from brew

### ISSUE THREAD

**Issue by pettyalex** [Gcenx/homebrew-wine#55]
When I try to install unofficial-wineskin with:
`brew install --no-quarantine gcenx/wine/unofficial-wineskin`, I see the error below. At a glance, it looks like maybe line 15 of unofficial-wineskin.rb needs to actually do a function call on ENV.fetch("USER") to get the USER environment variable? https://github.com/Gcenx/homebrew-wine/blob/master/Casks/unofficial-wineskin.rb#L15

https://ruby-doc.org/core-2.7.0/ENV.html#method-c-fetch

```
Error: wrong number of arguments (given 0, expected 1..2)
/opt/homebrew/Library/Taps/gcenx/homebrew-wine/Casks/unofficial-wineskin.rb:15:in `fetch'
/opt/homebrew/Library/Taps/gcenx/homebrew-wine/Casks/unofficial-wineskin.rb:15:in `block (2 levels) in load'
/opt/homebrew/Library/Homebrew/cask/artifact/abstract_flight_block.rb:45:in `instance_eval'
/opt/homebrew/Library/Homebrew/cask/artifact/abstract_flight_block.rb:45:in `abstract_phase'
/opt/homebrew/Library/Homebrew/cask/artifact/abstract_flight_block.rb:28:in `install_phase'
/opt/homebrew/Library/Homebrew/cask/installer.rb:240:in `block in install_artifacts'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/set.rb:777:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/set.rb:777:in `each'
/opt/homebrew/Library/Homebrew/cask/installer.rb:233:in `install_artifacts'
/opt/homebrew/Library/Homebrew/cask/installer.rb:110:in `install'
/opt/homebrew/Library/Homebrew/cask/cmd/install.rb:79:in `block in install_casks'
/opt/homebrew/Library/Homebrew/cask/cmd/install.rb:78:in `each'
/opt/homebrew/Library/Homebrew/cask/cmd/install.rb:78:in `install_casks'
/opt/homebrew/Library/Homebrew/cmd/install.rb:187:in `install'
/opt/homebrew/Library/Homebrew/brew.rb:93:in `<main>'
```

My environment is:
```
Homebrew 3.5.10-32-g4de6806
Homebrew/homebrew-core (git revision fe5136e61a9; last commit 2022-08-24)
Homebrew/homebrew-cask (git revision 19a8e40ba9; last commit 2022-08-24)
```
`ruby 2.6.8p205 (2021-07-07 revision 67951) [universal.arm64e-darwin21]`
`zsh 5.8.1 (x86_64-apple-darwin21.0)`

on an Apple M1 Macbook Air.

**Comment by Gcenx** [comment]
Hopefully that’s now correct, brews only tested required that prior change from the older working version _sigh_

**Comment by pettyalex** [comment]
Thank you for the prompt fix! it's working now. I know so little about Homebrew/ruby I was afraid I was making a bogus issue report.

```
==> Installing Cask unofficial-wineskin
Warning: macOS's Gatekeeper has been disabled for this Cask
==> Moving App 'Wineskin Winery.app' to '/Applications/Wineskin Winery.app'
🍺  unofficial-wineskin was successfully installed!
```

**Comment by Gcenx** [comment]
I’m really not familiar with ruby so I’m more lightly to make mistakes especially if brew testbot gives the OK and it’s wrong…
